[package]
name = "seaquel-engine-sqlite"
version = "0.1.0"
edition = "2021"
description = "SQLite engine for Seaquel."

[dependencies]
seaquel-engine = { path = "../seaquel-engine" }
seaquel-runtime = { path = "../seaquel-runtime" }
serde_json = { workspace = true }
sqlx = { workspace = true }
time = { workspace = true }

[dev-dependencies]
seaquel-engine-testkit = { path = "../seaquel-engine-testkit" }
serde_json = { workspace = true }
tokio = { version = "1", features = ["macros", "rt"] }
uuid = { workspace = true }
