//! `tests/fixtures/cells.json`: the typed-cell cases (`common/cells.rs`) as
//! JSON, with their native expectations in the cell wire format, for the
//! browser module's live suite (`src/lib/engine/engine-duckdb-browser.test.ts`),
//! which runs them through Core in the page against DuckDB-WASM.
//!
//! This test fails when the file no longer matches the cases. Rewrite it
//! with `SEAQUEL_RECORD_CELLS=1 cargo test -p seaquel-engine-duckdb --test
//! cells_fixture`. Scratch table names are numbered in order, so the file
//! doesn't change from run to run.

#[path = "common/cells.rs"]
mod cells;

use serde_json::{json, Value as Json};

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/cells.json");

/// `values_<32 hex>` (a `scratch_name`) as `values_<n>`, numbered by first
/// appearance across the whole file.
fn number_scratch_names(text: &str) -> String {
    let mut seen: Vec<String> = Vec::new();
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(at) = rest.find("values_") {
        let (before, from) = rest.split_at(at);
        out.push_str(before);
        let hex: String = from["values_".len()..]
            .chars()
            .take_while(|c| c.is_ascii_hexdigit())
            .collect();
        if hex.len() == 32 {
            let name = format!("values_{hex}");
            let n = match seen.iter().position(|s| *s == name) {
                Some(n) => n,
                None => {
                    seen.push(name);
                    seen.len() - 1
                }
            };
            out.push_str(&format!("values_{n}"));
            rest = &from["values_".len() + 32..];
        } else {
            out.push_str("values_");
            rest = &from["values_".len()..];
        }
    }
    out.push_str(rest);
    out
}

fn recorded() -> String {
    let cases: Vec<Json> = cells::cases()
        .into_iter()
        .map(|c| {
            json!({
                "name": c.name,
                "setup": c.setup,
                "teardown": c.teardown,
                "select": c.select,
                "expected": c.expected,
                "bindBack": c.bind_back,
            })
        })
        .collect();
    let text = serde_json::to_string_pretty(&json!({
        "about": "The typed-cell cases of crates/seaquel-engine-duckdb/tests/common/cells.rs with their native (duckdb-rs) values. Generated by tests/cells_fixture.rs; don't edit.",
        "cases": cases,
    }))
    .unwrap();
    number_scratch_names(&text) + "\n"
}

#[test]
fn the_cells_fixture_matches_the_cases() {
    let now = recorded();
    if std::env::var_os("SEAQUEL_RECORD_CELLS").is_some() {
        std::fs::write(FIXTURE, &now).unwrap();
        return;
    }
    let stored = std::fs::read_to_string(FIXTURE).unwrap_or_default();
    assert!(
        stored == now,
        "tests/fixtures/cells.json doesn't match tests/common/cells.rs; rewrite it with \
         SEAQUEL_RECORD_CELLS=1 cargo test -p seaquel-engine-duckdb --test cells_fixture"
    );
}

#[test]
fn scratch_names_are_numbered_in_order() {
    let a = "a".repeat(32);
    let b = "b".repeat(32);
    assert_eq!(
        number_scratch_names(&format!("values_{a} values_{b} values_{a} values_x")),
        "values_0 values_1 values_0 values_x"
    );
}
