[package]
name = "seaquel-engine-mssql"
version = "0.1.0"
edition = "2021"
description = "Microsoft SQL Server engine for Seaquel."

[dependencies]
seaquel-engine = { path = "../seaquel-engine" }
seaquel-runtime = { path = "../seaquel-runtime" }
futures = { workspace = true }
log = { workspace = true }
roxmltree = "0.20"
seaquel-types = { path = "../seaquel-types" }
serde_json = { workspace = true }
tiberius = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tokio-util = { workspace = true }

[dev-dependencies]
seaquel-engine-testkit = { path = "../seaquel-engine-testkit" }
serde = { workspace = true }
tokio = { version = "1", features = ["macros", "rt"] }
