// `sqlx::migrate!` embeds `migrations/` at compile time. Without this, adding
// or changing a migration file wouldn't rebuild the crate.
//
// It also writes `$OUT_DIR/migrations.rs`, the same files as a list for the
// in-memory executor's migrator (wasm32, phase 8 Decision 4), read with
// sqlx's rules: `<version>_<description>.sql`, the description with `_` as
// spaces, sorted by version. `src/migrations.rs` checks it against
// `sqlx::migrate!` natively.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=migrations");

    let dir =
        Path::new(&std::env::var("CARGO_MANIFEST_DIR").expect("set by cargo")).join("migrations");
    let mut found: Vec<(i64, String, String)> = Vec::new();
    for entry in std::fs::read_dir(&dir).expect("migrations/ is readable") {
        let path = entry.expect("a directory entry").path();
        if !path.is_file() {
            continue;
        }
        let name = path
            .file_name()
            .expect("a file name")
            .to_string_lossy()
            .into_owned();
        // sqlx: `splitn(2, '_')`, and only names ending in `.sql`.
        let Some((version, rest)) = name.split_once('_') else {
            continue;
        };
        if !rest.ends_with(".sql") {
            continue;
        }
        assert!(
            !rest.ends_with(".up.sql") && !rest.ends_with(".down.sql"),
            "{name}: reversible migrations aren't used"
        );
        let version: i64 = version
            .parse()
            .unwrap_or_else(|_| panic!("{name}: the version prefix must be an integer"));
        let description = rest.trim_end_matches(".sql").replace('_', " ");
        found.push((version, description, path.display().to_string()));
    }
    found.sort_by_key(|(v, _, _)| *v);

    let mut out = String::from(
        "/// Every migration in `migrations/`, by version (generated by `build.rs`).\n\
         pub(crate) const MIGRATIONS: &[Migration] = &[\n",
    );
    for (version, description, path) in &found {
        writeln!(
            out,
            "    Migration {{ version: {version}, description: {description:?}, sql: include_str!({path:?}) }},"
        )
        .expect("writing to a String");
    }
    out.push_str("];\n");
    let target = Path::new(&std::env::var("OUT_DIR").expect("set by cargo")).join("migrations.rs");
    std::fs::write(target, out).expect("OUT_DIR is writable");
}
